name: Infrastructure Setup
description:  Composite action for setting up infrastructure(terragrunt-infrastructure-repo-template-v2) 

inputs:
  environment: 
    description: Input for which environment we are working with
    required: true
  aws-region: 
      description: Input for which aws region we are working with
      required: true

outputs:
  script:
    description: 
    value: "Done"

runs: 
  using: "composite"
  defaults:
    run:
      shell: bash    
  steps: 
    - name: Starting Setup 
      run: echo "Starting composite action"

      - name: Include directory 01 - production
        run: cp -r '01 - production/.' ${{inputs.environment}}/${{inputs.aws-region}}/${{inputs.environment}}
           
      - name: Include directory 00 - development
        continue-on-error: true
        run: |
              if [ -d '00 - development' ]
              then
                cp -r '00 - development/.' ${{inputs.environment}}/${{inputs.aws-region}}/${{inputs.environment}}
              else
                echo "Directory does not exist"
              fi

      - name: install tree
        run: sudo apt-get install tree -y

      - name: run tree
        run: tree  ${{inputs.environment}}/ --dirsfirst

