name: Infracost Analysis
description:  Composite action for infracost analysis of Terraform/Terragrunt 


inputs:
  directory: 
    description:
    required: false
    default: dev/eu-west-2/dev
  aws-region:
    description:
    required: true
  aws-account-id:
    description:
    required: true
  ssh-key-shared-modules:
    description: 
    required: true
  infracost_creds: 
    description:
    required: true
  github-token:
    description: 
    required: true



outputs:
  script:
    description: 
    value: "Done"


runs: 
  using: "composite"

  steps:
    - name: Checkout head branch
      uses: actions/checkout@v2
      with:
        ref: '${{ github.event.pull_request.head.ref }}'

    - name: Include directory 01 - production
      shell: bash
      run: cp -r '01 - production/.' ${{inputs.directory}}

    - name: Setting up AWS and Terraform
      uses: awazevr/devops-actions/aws-terragrunt-setup-action@main
      with:
        aws-region: ${{ inputs.aws-region }}
        aws-account-id: ${{ inputs.aws-account-id }} 
        ssh-key-shared-modules: ${{ inputs.ssh-key-shared-modules }}
        gh-pat: ${{ inputs.github-token}}
    
    - name: Setup Infracost
      uses: infracost/actions/setup@v2
      with:
        api-key: ${{ inputs.infracost_creds }}

       # Generate Infracost JSON file as the baseline.
    - name: Generate Infracost cost estimate baseline
      shell: bash
      run: |
        infracost breakdown --path="${{inputs.directory}}" \
                            --format=json \
                            --usage-file infracost-usage.yml \
                            --out-file=/tmp/infracost-base.json


    # - name: Generate Infracost cost estimate baseline
    #   run: |
    #     infracost breakdown --path=${TF_ROOT} \
    #                         --format=json \
    #                         --out-file=/tmp/infracost-base.json

    # - name: Checkout PR branch
    #   uses: actions/checkout@v2

    - name: Generate Infracost diff
      shell: bash
      run: |
        infracost diff --path=${{inputs.directory}} \
                        --format=json \
                        --usage-file infracost-usage.yml \
                        --compare-to=/tmp/infracost-base.json \
                        --out-file=/tmp/infracost.json

    - name: Post Infracost comment
      shell: bash
      run: |
          ls /tmp/
          infracost comment github --path=/tmp/infracost.json \
                                    --repo=$GITHUB_REPOSITORY \
                                    --github-token=${{inputs.github-token}} \
                                    --pull-request=${{github.event.pull_request.number}} \
                                    --behavior=update


    - name: Annotate Code Linting Results
      working-directory: ./tmp
      uses: ataylorme/eslint-annotate-action@v2
      with:
        repo-token: "${{ inputs.github-token}}"
        report-json: "infracost.json"

    # - name: Annotate
    #   uses: yuzutech/annotations-action@v0.4.0
    #   with:
    #     repo-token: "${{inputs.github-token}}"
    #     title: 'Infracost'
    #     input: '/tmp/infracost.json'