name: Reusable workflow example

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  release:
    name: 'Create release'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      security-events: write
      pull-requests: write
      actions: read
    steps:
      - uses: actions/checkout@master
      
      - name: Create New Relic deployment marker
        uses: newrelic/deployment-marker-action@v1
        with:
          apiKey: ${{ inputs.newrelic-api-key }}
          accountId: ${{ inputs.newrelic-account-id }}
          applicationId: ${{ inputs.newrelic-application }}
          revision: "${{ inputs.release-version }}"
